/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCompaniesRouteImport } from './routes/_app.companies'
import { Route as AppCommandRouteImport } from './routes/_app.command'
import { Route as AppActivitiesRouteImport } from './routes/_app.activities'
import { Route as ApiPublicInboundEmailRouteImport } from './routes/api/public/inbound-email'
import { Route as AppSettingsWebhooksRouteImport } from './routes/_app.settings.webhooks'
import { Route as AppSettingsOrganizationRouteImport } from './routes/_app.settings.organization'
import { Route as AppSettingsImportRouteImport } from './routes/_app.settings.import'
import { Route as AppSettingsFieldsRouteImport } from './routes/_app.settings.fields'
import { Route as AppSettingsAutomationsRouteImport } from './routes/_app.settings.automations'
import { Route as AppInviteTokenRouteImport } from './routes/_app.invite.$token'
import { Route as AppContactsIdRouteImport } from './routes/_app.contacts.$id'
import { Route as AppCompaniesIdRouteImport } from './routes/_app.companies.$id'
import { Route as ApiPublicHooksActivityRemindersRouteImport } from './routes/api/public/hooks/activity-reminders'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandRoute = AppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicInboundEmailRoute = ApiPublicInboundEmailRouteImport.update({
  id: '/api/public/inbound-email',
  path: '/api/public/inbound-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsWebhooksRoute = AppSettingsWebhooksRouteImport.update({
  id: '/settings/webhooks',
  path: '/settings/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsImportRoute = AppSettingsImportRouteImport.update({
  id: '/settings/import',
  path: '/settings/import',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsFieldsRoute = AppSettingsFieldsRouteImport.update({
  id: '/settings/fields',
  path: '/settings/fields',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAutomationsRoute = AppSettingsAutomationsRouteImport.update({
  id: '/settings/automations',
  path: '/settings/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteTokenRoute = AppInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppCompaniesIdRoute = AppCompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCompaniesRoute,
} as any)
const ApiPublicHooksActivityRemindersRoute =
  ApiPublicHooksActivityRemindersRouteImport.update({
    id: '/api/public/hooks/activity-reminders',
    path: '/api/public/hooks/activity-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AppActivitiesRoute
  '/command': typeof AppCommandRoute
  '/companies': typeof AppCompaniesRouteWithChildren
  '/contacts': typeof AppContactsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/companies/$id': typeof AppCompaniesIdRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/settings/automations': typeof AppSettingsAutomationsRoute
  '/settings/fields': typeof AppSettingsFieldsRoute
  '/settings/import': typeof AppSettingsImportRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/hooks/activity-reminders': typeof ApiPublicHooksActivityRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AppActivitiesRoute
  '/command': typeof AppCommandRoute
  '/companies': typeof AppCompaniesRouteWithChildren
  '/contacts': typeof AppContactsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/companies/$id': typeof AppCompaniesIdRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/settings/automations': typeof AppSettingsAutomationsRoute
  '/settings/fields': typeof AppSettingsFieldsRoute
  '/settings/import': typeof AppSettingsImportRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/hooks/activity-reminders': typeof ApiPublicHooksActivityRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/command': typeof AppCommandRoute
  '/_app/companies': typeof AppCompaniesRouteWithChildren
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/companies/$id': typeof AppCompaniesIdRoute
  '/_app/contacts/$id': typeof AppContactsIdRoute
  '/_app/invite/$token': typeof AppInviteTokenRoute
  '/_app/settings/automations': typeof AppSettingsAutomationsRoute
  '/_app/settings/fields': typeof AppSettingsFieldsRoute
  '/_app/settings/import': typeof AppSettingsImportRoute
  '/_app/settings/organization': typeof AppSettingsOrganizationRoute
  '/_app/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/hooks/activity-reminders': typeof ApiPublicHooksActivityRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activities'
    | '/command'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/pipeline'
    | '/reports'
    | '/companies/$id'
    | '/contacts/$id'
    | '/invite/$token'
    | '/settings/automations'
    | '/settings/fields'
    | '/settings/import'
    | '/settings/organization'
    | '/settings/webhooks'
    | '/api/public/inbound-email'
    | '/api/public/hooks/activity-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activities'
    | '/command'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/pipeline'
    | '/reports'
    | '/companies/$id'
    | '/contacts/$id'
    | '/invite/$token'
    | '/settings/automations'
    | '/settings/fields'
    | '/settings/import'
    | '/settings/organization'
    | '/settings/webhooks'
    | '/api/public/inbound-email'
    | '/api/public/hooks/activity-reminders'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/activities'
    | '/_app/command'
    | '/_app/companies'
    | '/_app/contacts'
    | '/_app/dashboard'
    | '/_app/pipeline'
    | '/_app/reports'
    | '/_app/companies/$id'
    | '/_app/contacts/$id'
    | '/_app/invite/$token'
    | '/_app/settings/automations'
    | '/_app/settings/fields'
    | '/_app/settings/import'
    | '/_app/settings/organization'
    | '/_app/settings/webhooks'
    | '/api/public/inbound-email'
    | '/api/public/hooks/activity-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicInboundEmailRoute: typeof ApiPublicInboundEmailRoute
  ApiPublicHooksActivityRemindersRoute: typeof ApiPublicHooksActivityRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/command': {
      id: '/_app/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AppCommandRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/inbound-email': {
      id: '/api/public/inbound-email'
      path: '/api/public/inbound-email'
      fullPath: '/api/public/inbound-email'
      preLoaderRoute: typeof ApiPublicInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/webhooks': {
      id: '/_app/settings/webhooks'
      path: '/settings/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AppSettingsWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/import': {
      id: '/_app/settings/import'
      path: '/settings/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof AppSettingsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/fields': {
      id: '/_app/settings/fields'
      path: '/settings/fields'
      fullPath: '/settings/fields'
      preLoaderRoute: typeof AppSettingsFieldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/automations': {
      id: '/_app/settings/automations'
      path: '/settings/automations'
      fullPath: '/settings/automations'
      preLoaderRoute: typeof AppSettingsAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite/$token': {
      id: '/_app/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AppInviteTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/$id': {
      id: '/_app/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/companies/$id': {
      id: '/_app/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AppCompaniesIdRouteImport
      parentRoute: typeof AppCompaniesRoute
    }
    '/api/public/hooks/activity-reminders': {
      id: '/api/public/hooks/activity-reminders'
      path: '/api/public/hooks/activity-reminders'
      fullPath: '/api/public/hooks/activity-reminders'
      preLoaderRoute: typeof ApiPublicHooksActivityRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCompaniesRouteChildren {
  AppCompaniesIdRoute: typeof AppCompaniesIdRoute
}

const AppCompaniesRouteChildren: AppCompaniesRouteChildren = {
  AppCompaniesIdRoute: AppCompaniesIdRoute,
}

const AppCompaniesRouteWithChildren = AppCompaniesRoute._addFileChildren(
  AppCompaniesRouteChildren,
)

interface AppContactsRouteChildren {
  AppContactsIdRoute: typeof AppContactsIdRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsIdRoute: AppContactsIdRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppCommandRoute: typeof AppCommandRoute
  AppCompaniesRoute: typeof AppCompaniesRouteWithChildren
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppReportsRoute: typeof AppReportsRoute
  AppInviteTokenRoute: typeof AppInviteTokenRoute
  AppSettingsAutomationsRoute: typeof AppSettingsAutomationsRoute
  AppSettingsFieldsRoute: typeof AppSettingsFieldsRoute
  AppSettingsImportRoute: typeof AppSettingsImportRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppSettingsWebhooksRoute: typeof AppSettingsWebhooksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppCommandRoute: AppCommandRoute,
  AppCompaniesRoute: AppCompaniesRouteWithChildren,
  AppContactsRoute: AppContactsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppReportsRoute: AppReportsRoute,
  AppInviteTokenRoute: AppInviteTokenRoute,
  AppSettingsAutomationsRoute: AppSettingsAutomationsRoute,
  AppSettingsFieldsRoute: AppSettingsFieldsRoute,
  AppSettingsImportRoute: AppSettingsImportRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppSettingsWebhooksRoute: AppSettingsWebhooksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicInboundEmailRoute: ApiPublicInboundEmailRoute,
  ApiPublicHooksActivityRemindersRoute: ApiPublicHooksActivityRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
