/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as AppWinLossRouteImport } from './routes/_app.win-loss'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppWelcomeRouteImport } from './routes/_app.welcome'
import { Route as AppSiteChatRouteImport } from './routes/_app.site-chat'
import { Route as AppSetupWizardRouteImport } from './routes/_app.setup-wizard'
import { Route as AppSequencesRouteImport } from './routes/_app.sequences'
import { Route as AppRetentionRouteImport } from './routes/_app.retention'
import { Route as AppRepresentantesRouteImport } from './routes/_app.representantes'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppOportunidadesRouteImport } from './routes/_app.oportunidades'
import { Route as AppNbaRouteImport } from './routes/_app.nba'
import { Route as AppMytasksRouteImport } from './routes/_app.mytasks'
import { Route as AppMultiEmpresaRouteImport } from './routes/_app.multi-empresa'
import { Route as AppMeuDiaRouteImport } from './routes/_app.meu-dia'
import { Route as AppMarketingIntelRouteImport } from './routes/_app.marketing-intel'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppLeadFormsRouteImport } from './routes/_app.lead-forms'
import { Route as AppInteligenciaComercialRouteImport } from './routes/_app.inteligencia-comercial'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppInfluencersRouteImport } from './routes/_app.influencers'
import { Route as AppGoalsRouteImport } from './routes/_app.goals'
import { Route as AppGestaoVisaoGlobalRouteImport } from './routes/_app.gestao-visao-global'
import { Route as AppGeoRotaRouteImport } from './routes/_app.geo-rota'
import { Route as AppGeoProspeccaoRouteImport } from './routes/_app.geo-prospeccao'
import { Route as AppGeoCoberturaRouteImport } from './routes/_app.geo-cobertura'
import { Route as AppGeoRouteImport } from './routes/_app.geo'
import { Route as AppForecastRouteImport } from './routes/_app.forecast'
import { Route as AppDashboardExecutivoRouteImport } from './routes/_app.dashboard-executivo'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomer360RouteImport } from './routes/_app.customer-360'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCompaniesRouteImport } from './routes/_app.companies'
import { Route as AppCommissionsRouteImport } from './routes/_app.commissions'
import { Route as AppCommandRouteImport } from './routes/_app.command'
import { Route as AppCoachingRouteImport } from './routes/_app.coaching'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCarteiraRouteImport } from './routes/_app.carteira'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAutomacoesRouteImport } from './routes/_app.automacoes'
import { Route as AppActivitiesRouteImport } from './routes/_app.activities'
import { Route as IOrgSlugRouteImport } from './routes/i.$org.$slug'
import { Route as ApiPublicSiteChatWidgetDotjsRouteImport } from './routes/api/public/site-chat-widget[.]js'
import { Route as ApiPublicSiteChatRouteImport } from './routes/api/public/site-chat'
import { Route as ApiPublicLeadFormRouteImport } from './routes/api/public/lead-form'
import { Route as ApiPublicInfluencerVisitRouteImport } from './routes/api/public/influencer-visit'
import { Route as ApiPublicInboundEmailRouteImport } from './routes/api/public/inbound-email'
import { Route as AppSettingsWhatsappRouteImport } from './routes/_app.settings.whatsapp'
import { Route as AppSettingsWebhooksRouteImport } from './routes/_app.settings.webhooks'
import { Route as AppSettingsSiteChatRouteImport } from './routes/_app.settings.site-chat'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app.settings.security'
import { Route as AppSettingsOrganizationRouteImport } from './routes/_app.settings.organization'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsImportRouteImport } from './routes/_app.settings.import'
import { Route as AppSettingsFieldsRouteImport } from './routes/_app.settings.fields'
import { Route as AppSettingsErpAgentRouteImport } from './routes/_app.settings.erp-agent'
import { Route as AppSettingsBriefingRouteImport } from './routes/_app.settings.briefing'
import { Route as AppSettingsAutomationsRouteImport } from './routes/_app.settings.automations'
import { Route as AppSettingsAlertsRouteImport } from './routes/_app.settings.alerts'
import { Route as AppSequencesIdRouteImport } from './routes/_app.sequences.$id'
import { Route as AppReportsWeeklyRouteImport } from './routes/_app.reports.weekly'
import { Route as AppReportsDashboardsRouteImport } from './routes/_app.reports.dashboards'
import { Route as AppMultiEmpresaOrgIdRouteImport } from './routes/_app.multi-empresa.$orgId'
import { Route as AppInviteTokenRouteImport } from './routes/_app.invite.$token'
import { Route as AppInteligenciaComercialQualidadeIaRouteImport } from './routes/_app.inteligencia-comercial.qualidade-ia'
import { Route as AppIntegrationsTemplatesRouteImport } from './routes/_app.integrations.templates'
import { Route as AppIntegrationsSmokeTestRouteImport } from './routes/_app.integrations.smoke-test'
import { Route as AppIntegrationsOutboxRouteImport } from './routes/_app.integrations.outbox'
import { Route as AppIntegrationsMappingRouteImport } from './routes/_app.integrations.mapping'
import { Route as AppIntegrationsHelpRouteImport } from './routes/_app.integrations.help'
import { Route as AppIntegrationsHealthRouteImport } from './routes/_app.integrations.health'
import { Route as AppIntegrationsDiagnosticRouteImport } from './routes/_app.integrations.diagnostic'
import { Route as AppIntegrationsDashboardRouteImport } from './routes/_app.integrations.dashboard'
import { Route as AppIntegrationsConnectRouteImport } from './routes/_app.integrations.connect'
import { Route as AppIntegrationsConflictsRouteImport } from './routes/_app.integrations.conflicts'
import { Route as AppIntegrationsAppsRouteImport } from './routes/_app.integrations.apps'
import { Route as AppIntegrationsAgentRouteImport } from './routes/_app.integrations.agent'
import { Route as AppIntegrationsAdvancedRouteImport } from './routes/_app.integrations.advanced'
import { Route as AppContactsIdRouteImport } from './routes/_app.contacts.$id'
import { Route as AppCompaniesIdRouteImport } from './routes/_app.companies.$id'
import { Route as AppCampaignsWhatsappRouteImport } from './routes/_app.campaigns.whatsapp'
import { Route as ApiPublicHooksWhatsappOutboxTickRouteImport } from './routes/api/public/hooks/whatsapp-outbox-tick'
import { Route as ApiPublicHooksSequenceTickRouteImport } from './routes/api/public/hooks/sequence-tick'
import { Route as ApiPublicHooksRefreshRecommendationsRouteImport } from './routes/api/public/hooks/refresh-recommendations'
import { Route as ApiPublicHooksPropensityBatchTickRouteImport } from './routes/api/public/hooks/propensity-batch-tick'
import { Route as ApiPublicHooksGenerateAlertsRouteImport } from './routes/api/public/hooks/generate-alerts'
import { Route as ApiPublicHooksErpSyncTickRouteImport } from './routes/api/public/hooks/erp-sync-tick'
import { Route as ApiPublicHooksErpOutboxTickRouteImport } from './routes/api/public/hooks/erp-outbox-tick'
import { Route as ApiPublicHooksErpLocalAgentPairRouteImport } from './routes/api/public/hooks/erp-local-agent-pair'
import { Route as ApiPublicHooksErpLocalAgentHeartbeatRouteImport } from './routes/api/public/hooks/erp-local-agent-heartbeat'
import { Route as ApiPublicHooksErpInboundRouteImport } from './routes/api/public/hooks/erp-inbound'
import { Route as ApiPublicHooksErpAgentPushRouteImport } from './routes/api/public/hooks/erp-agent-push'
import { Route as ApiPublicHooksDailyBriefingRouteImport } from './routes/api/public/hooks/daily-briefing'
import { Route as ApiPublicHooksCustomer360RefreshRouteImport } from './routes/api/public/hooks/customer-360-refresh'
import { Route as ApiPublicHooksCampaignTickRouteImport } from './routes/api/public/hooks/campaign-tick'
import { Route as ApiPublicHooksAiPurgeExpiredRouteImport } from './routes/api/public/hooks/ai-purge-expired'
import { Route as ApiPublicHooksActivityRemindersRouteImport } from './routes/api/public/hooks/activity-reminders'
import { Route as ApiOauthGoogleInitiateRouteImport } from './routes/api.oauth.google.initiate'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api.oauth.google.callback'
import { Route as AppSettingsAutomationsRunsRouteImport } from './routes/_app.settings.automations.runs'
import { Route as AppReportsDashboardsIdRouteImport } from './routes/_app.reports.dashboards.$id'
import { Route as AppIntegrationsConnectWizardRouteImport } from './routes/_app.integrations.connect.wizard'
import { Route as ApiPublicHooksWhatsappWebhookChannelIdRouteImport } from './routes/api/public/hooks/whatsapp-webhook.$channelId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWinLossRoute = AppWinLossRouteImport.update({
  id: '/win-loss',
  path: '/win-loss',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteChatRoute = AppSiteChatRouteImport.update({
  id: '/site-chat',
  path: '/site-chat',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupWizardRoute = AppSetupWizardRouteImport.update({
  id: '/setup-wizard',
  path: '/setup-wizard',
  getParentRoute: () => AppRoute,
} as any)
const AppSequencesRoute = AppSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => AppRoute,
} as any)
const AppRetentionRoute = AppRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AppRoute,
} as any)
const AppRepresentantesRoute = AppRepresentantesRouteImport.update({
  id: '/representantes',
  path: '/representantes',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppOportunidadesRoute = AppOportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => AppRoute,
} as any)
const AppNbaRoute = AppNbaRouteImport.update({
  id: '/nba',
  path: '/nba',
  getParentRoute: () => AppRoute,
} as any)
const AppMytasksRoute = AppMytasksRouteImport.update({
  id: '/mytasks',
  path: '/mytasks',
  getParentRoute: () => AppRoute,
} as any)
const AppMultiEmpresaRoute = AppMultiEmpresaRouteImport.update({
  id: '/multi-empresa',
  path: '/multi-empresa',
  getParentRoute: () => AppRoute,
} as any)
const AppMeuDiaRoute = AppMeuDiaRouteImport.update({
  id: '/meu-dia',
  path: '/meu-dia',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingIntelRoute = AppMarketingIntelRouteImport.update({
  id: '/marketing-intel',
  path: '/marketing-intel',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadFormsRoute = AppLeadFormsRouteImport.update({
  id: '/lead-forms',
  path: '/lead-forms',
  getParentRoute: () => AppRoute,
} as any)
const AppInteligenciaComercialRoute =
  AppInteligenciaComercialRouteImport.update({
    id: '/inteligencia-comercial',
    path: '/inteligencia-comercial',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInfluencersRoute = AppInfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoVisaoGlobalRoute = AppGestaoVisaoGlobalRouteImport.update({
  id: '/gestao-visao-global',
  path: '/gestao-visao-global',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoRotaRoute = AppGeoRotaRouteImport.update({
  id: '/geo-rota',
  path: '/geo-rota',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoProspeccaoRoute = AppGeoProspeccaoRouteImport.update({
  id: '/geo-prospeccao',
  path: '/geo-prospeccao',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoCoberturaRoute = AppGeoCoberturaRouteImport.update({
  id: '/geo-cobertura',
  path: '/geo-cobertura',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoRoute = AppGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardExecutivoRoute = AppDashboardExecutivoRouteImport.update({
  id: '/dashboard-executivo',
  path: '/dashboard-executivo',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomer360Route = AppCustomer360RouteImport.update({
  id: '/customer-360',
  path: '/customer-360',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandRoute = AppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachingRoute = AppCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCarteiraRoute = AppCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const IOrgSlugRoute = IOrgSlugRouteImport.update({
  id: '/i/$org/$slug',
  path: '/i/$org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteChatWidgetDotjsRoute =
  ApiPublicSiteChatWidgetDotjsRouteImport.update({
    id: '/api/public/site-chat-widget.js',
    path: '/api/public/site-chat-widget.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSiteChatRoute = ApiPublicSiteChatRouteImport.update({
  id: '/api/public/site-chat',
  path: '/api/public/site-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadFormRoute = ApiPublicLeadFormRouteImport.update({
  id: '/api/public/lead-form',
  path: '/api/public/lead-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInfluencerVisitRoute =
  ApiPublicInfluencerVisitRouteImport.update({
    id: '/api/public/influencer-visit',
    path: '/api/public/influencer-visit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInboundEmailRoute = ApiPublicInboundEmailRouteImport.update({
  id: '/api/public/inbound-email',
  path: '/api/public/inbound-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsWhatsappRoute = AppSettingsWhatsappRouteImport.update({
  id: '/settings/whatsapp',
  path: '/settings/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsWebhooksRoute = AppSettingsWebhooksRouteImport.update({
  id: '/settings/webhooks',
  path: '/settings/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSiteChatRoute = AppSettingsSiteChatRouteImport.update({
  id: '/settings/site-chat',
  path: '/settings/site-chat',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsImportRoute = AppSettingsImportRouteImport.update({
  id: '/settings/import',
  path: '/settings/import',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsFieldsRoute = AppSettingsFieldsRouteImport.update({
  id: '/settings/fields',
  path: '/settings/fields',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsErpAgentRoute = AppSettingsErpAgentRouteImport.update({
  id: '/settings/erp-agent',
  path: '/settings/erp-agent',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBriefingRoute = AppSettingsBriefingRouteImport.update({
  id: '/settings/briefing',
  path: '/settings/briefing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAutomationsRoute = AppSettingsAutomationsRouteImport.update({
  id: '/settings/automations',
  path: '/settings/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAlertsRoute = AppSettingsAlertsRouteImport.update({
  id: '/settings/alerts',
  path: '/settings/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppSequencesIdRoute = AppSequencesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSequencesRoute,
} as any)
const AppReportsWeeklyRoute = AppReportsWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsDashboardsRoute = AppReportsDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppMultiEmpresaOrgIdRoute = AppMultiEmpresaOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AppMultiEmpresaRoute,
} as any)
const AppInviteTokenRoute = AppInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppInteligenciaComercialQualidadeIaRoute =
  AppInteligenciaComercialQualidadeIaRouteImport.update({
    id: '/qualidade-ia',
    path: '/qualidade-ia',
    getParentRoute: () => AppInteligenciaComercialRoute,
  } as any)
const AppIntegrationsTemplatesRoute =
  AppIntegrationsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AppIntegrationsRoute,
  } as any)
const AppIntegrationsSmokeTestRoute =
  AppIntegrationsSmokeTestRouteImport.update({
    id: '/smoke-test',
    path: '/smoke-test',
    getParentRoute: () => AppIntegrationsRoute,
  } as any)
const AppIntegrationsOutboxRoute = AppIntegrationsOutboxRouteImport.update({
  id: '/outbox',
  path: '/outbox',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppIntegrationsMappingRoute = AppIntegrationsMappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppIntegrationsHelpRoute = AppIntegrationsHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppIntegrationsHealthRoute = AppIntegrationsHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppIntegrationsDiagnosticRoute =
  AppIntegrationsDiagnosticRouteImport.update({
    id: '/diagnostic',
    path: '/diagnostic',
    getParentRoute: () => AppIntegrationsRoute,
  } as any)
const AppIntegrationsDashboardRoute =
  AppIntegrationsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppIntegrationsRoute,
  } as any)
const AppIntegrationsConnectRoute = AppIntegrationsConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppIntegrationsConflictsRoute =
  AppIntegrationsConflictsRouteImport.update({
    id: '/conflicts',
    path: '/conflicts',
    getParentRoute: () => AppIntegrationsRoute,
  } as any)
const AppIntegrationsAppsRoute = AppIntegrationsAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppIntegrationsAgentRoute = AppIntegrationsAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppIntegrationsAdvancedRoute = AppIntegrationsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppCompaniesIdRoute = AppCompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCompaniesRoute,
} as any)
const AppCampaignsWhatsappRoute = AppCampaignsWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const ApiPublicHooksWhatsappOutboxTickRoute =
  ApiPublicHooksWhatsappOutboxTickRouteImport.update({
    id: '/api/public/hooks/whatsapp-outbox-tick',
    path: '/api/public/hooks/whatsapp-outbox-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSequenceTickRoute =
  ApiPublicHooksSequenceTickRouteImport.update({
    id: '/api/public/hooks/sequence-tick',
    path: '/api/public/hooks/sequence-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshRecommendationsRoute =
  ApiPublicHooksRefreshRecommendationsRouteImport.update({
    id: '/api/public/hooks/refresh-recommendations',
    path: '/api/public/hooks/refresh-recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPropensityBatchTickRoute =
  ApiPublicHooksPropensityBatchTickRouteImport.update({
    id: '/api/public/hooks/propensity-batch-tick',
    path: '/api/public/hooks/propensity-batch-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateAlertsRoute =
  ApiPublicHooksGenerateAlertsRouteImport.update({
    id: '/api/public/hooks/generate-alerts',
    path: '/api/public/hooks/generate-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksErpSyncTickRoute =
  ApiPublicHooksErpSyncTickRouteImport.update({
    id: '/api/public/hooks/erp-sync-tick',
    path: '/api/public/hooks/erp-sync-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksErpOutboxTickRoute =
  ApiPublicHooksErpOutboxTickRouteImport.update({
    id: '/api/public/hooks/erp-outbox-tick',
    path: '/api/public/hooks/erp-outbox-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksErpLocalAgentPairRoute =
  ApiPublicHooksErpLocalAgentPairRouteImport.update({
    id: '/api/public/hooks/erp-local-agent-pair',
    path: '/api/public/hooks/erp-local-agent-pair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksErpLocalAgentHeartbeatRoute =
  ApiPublicHooksErpLocalAgentHeartbeatRouteImport.update({
    id: '/api/public/hooks/erp-local-agent-heartbeat',
    path: '/api/public/hooks/erp-local-agent-heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksErpInboundRoute =
  ApiPublicHooksErpInboundRouteImport.update({
    id: '/api/public/hooks/erp-inbound',
    path: '/api/public/hooks/erp-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksErpAgentPushRoute =
  ApiPublicHooksErpAgentPushRouteImport.update({
    id: '/api/public/hooks/erp-agent-push',
    path: '/api/public/hooks/erp-agent-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyBriefingRoute =
  ApiPublicHooksDailyBriefingRouteImport.update({
    id: '/api/public/hooks/daily-briefing',
    path: '/api/public/hooks/daily-briefing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCustomer360RefreshRoute =
  ApiPublicHooksCustomer360RefreshRouteImport.update({
    id: '/api/public/hooks/customer-360-refresh',
    path: '/api/public/hooks/customer-360-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCampaignTickRoute =
  ApiPublicHooksCampaignTickRouteImport.update({
    id: '/api/public/hooks/campaign-tick',
    path: '/api/public/hooks/campaign-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAiPurgeExpiredRoute =
  ApiPublicHooksAiPurgeExpiredRouteImport.update({
    id: '/api/public/hooks/ai-purge-expired',
    path: '/api/public/hooks/ai-purge-expired',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksActivityRemindersRoute =
  ApiPublicHooksActivityRemindersRouteImport.update({
    id: '/api/public/hooks/activity-reminders',
    path: '/api/public/hooks/activity-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthGoogleInitiateRoute = ApiOauthGoogleInitiateRouteImport.update({
  id: '/api/oauth/google/initiate',
  path: '/api/oauth/google/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsAutomationsRunsRoute =
  AppSettingsAutomationsRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AppSettingsAutomationsRoute,
  } as any)
const AppReportsDashboardsIdRoute = AppReportsDashboardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReportsDashboardsRoute,
} as any)
const AppIntegrationsConnectWizardRoute =
  AppIntegrationsConnectWizardRouteImport.update({
    id: '/wizard',
    path: '/wizard',
    getParentRoute: () => AppIntegrationsConnectRoute,
  } as any)
const ApiPublicHooksWhatsappWebhookChannelIdRoute =
  ApiPublicHooksWhatsappWebhookChannelIdRouteImport.update({
    id: '/api/public/hooks/whatsapp-webhook/$channelId',
    path: '/api/public/hooks/whatsapp-webhook/$channelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AppActivitiesRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/calendar': typeof AppCalendarRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/carteira': typeof AppCarteiraRoute
  '/chat': typeof AppChatRoute
  '/coaching': typeof AppCoachingRoute
  '/command': typeof AppCommandRoute
  '/commissions': typeof AppCommissionsRoute
  '/companies': typeof AppCompaniesRouteWithChildren
  '/contacts': typeof AppContactsRouteWithChildren
  '/customer-360': typeof AppCustomer360Route
  '/dashboard': typeof AppDashboardRoute
  '/dashboard-executivo': typeof AppDashboardExecutivoRoute
  '/forecast': typeof AppForecastRoute
  '/geo': typeof AppGeoRoute
  '/geo-cobertura': typeof AppGeoCoberturaRoute
  '/geo-prospeccao': typeof AppGeoProspeccaoRoute
  '/geo-rota': typeof AppGeoRotaRoute
  '/gestao-visao-global': typeof AppGestaoVisaoGlobalRoute
  '/goals': typeof AppGoalsRoute
  '/influencers': typeof AppInfluencersRoute
  '/integrations': typeof AppIntegrationsRouteWithChildren
  '/inteligencia-comercial': typeof AppInteligenciaComercialRouteWithChildren
  '/lead-forms': typeof AppLeadFormsRoute
  '/leads': typeof AppLeadsRoute
  '/marketing-intel': typeof AppMarketingIntelRoute
  '/meu-dia': typeof AppMeuDiaRoute
  '/multi-empresa': typeof AppMultiEmpresaRouteWithChildren
  '/mytasks': typeof AppMytasksRoute
  '/nba': typeof AppNbaRoute
  '/oportunidades': typeof AppOportunidadesRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/representantes': typeof AppRepresentantesRoute
  '/retention': typeof AppRetentionRoute
  '/sequences': typeof AppSequencesRouteWithChildren
  '/setup-wizard': typeof AppSetupWizardRoute
  '/site-chat': typeof AppSiteChatRoute
  '/welcome': typeof AppWelcomeRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/win-loss': typeof AppWinLossRoute
  '/p/$token': typeof PTokenRoute
  '/campaigns/whatsapp': typeof AppCampaignsWhatsappRoute
  '/companies/$id': typeof AppCompaniesIdRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/integrations/advanced': typeof AppIntegrationsAdvancedRoute
  '/integrations/agent': typeof AppIntegrationsAgentRoute
  '/integrations/apps': typeof AppIntegrationsAppsRoute
  '/integrations/conflicts': typeof AppIntegrationsConflictsRoute
  '/integrations/connect': typeof AppIntegrationsConnectRouteWithChildren
  '/integrations/dashboard': typeof AppIntegrationsDashboardRoute
  '/integrations/diagnostic': typeof AppIntegrationsDiagnosticRoute
  '/integrations/health': typeof AppIntegrationsHealthRoute
  '/integrations/help': typeof AppIntegrationsHelpRoute
  '/integrations/mapping': typeof AppIntegrationsMappingRoute
  '/integrations/outbox': typeof AppIntegrationsOutboxRoute
  '/integrations/smoke-test': typeof AppIntegrationsSmokeTestRoute
  '/integrations/templates': typeof AppIntegrationsTemplatesRoute
  '/inteligencia-comercial/qualidade-ia': typeof AppInteligenciaComercialQualidadeIaRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/multi-empresa/$orgId': typeof AppMultiEmpresaOrgIdRoute
  '/reports/dashboards': typeof AppReportsDashboardsRouteWithChildren
  '/reports/weekly': typeof AppReportsWeeklyRoute
  '/sequences/$id': typeof AppSequencesIdRoute
  '/settings/alerts': typeof AppSettingsAlertsRoute
  '/settings/automations': typeof AppSettingsAutomationsRouteWithChildren
  '/settings/briefing': typeof AppSettingsBriefingRoute
  '/settings/erp-agent': typeof AppSettingsErpAgentRoute
  '/settings/fields': typeof AppSettingsFieldsRoute
  '/settings/import': typeof AppSettingsImportRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/site-chat': typeof AppSettingsSiteChatRoute
  '/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/settings/whatsapp': typeof AppSettingsWhatsappRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/influencer-visit': typeof ApiPublicInfluencerVisitRoute
  '/api/public/lead-form': typeof ApiPublicLeadFormRoute
  '/api/public/site-chat': typeof ApiPublicSiteChatRoute
  '/api/public/site-chat-widget.js': typeof ApiPublicSiteChatWidgetDotjsRoute
  '/i/$org/$slug': typeof IOrgSlugRoute
  '/integrations/connect/wizard': typeof AppIntegrationsConnectWizardRoute
  '/reports/dashboards/$id': typeof AppReportsDashboardsIdRoute
  '/settings/automations/runs': typeof AppSettingsAutomationsRunsRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/initiate': typeof ApiOauthGoogleInitiateRoute
  '/api/public/hooks/activity-reminders': typeof ApiPublicHooksActivityRemindersRoute
  '/api/public/hooks/ai-purge-expired': typeof ApiPublicHooksAiPurgeExpiredRoute
  '/api/public/hooks/campaign-tick': typeof ApiPublicHooksCampaignTickRoute
  '/api/public/hooks/customer-360-refresh': typeof ApiPublicHooksCustomer360RefreshRoute
  '/api/public/hooks/daily-briefing': typeof ApiPublicHooksDailyBriefingRoute
  '/api/public/hooks/erp-agent-push': typeof ApiPublicHooksErpAgentPushRoute
  '/api/public/hooks/erp-inbound': typeof ApiPublicHooksErpInboundRoute
  '/api/public/hooks/erp-local-agent-heartbeat': typeof ApiPublicHooksErpLocalAgentHeartbeatRoute
  '/api/public/hooks/erp-local-agent-pair': typeof ApiPublicHooksErpLocalAgentPairRoute
  '/api/public/hooks/erp-outbox-tick': typeof ApiPublicHooksErpOutboxTickRoute
  '/api/public/hooks/erp-sync-tick': typeof ApiPublicHooksErpSyncTickRoute
  '/api/public/hooks/generate-alerts': typeof ApiPublicHooksGenerateAlertsRoute
  '/api/public/hooks/propensity-batch-tick': typeof ApiPublicHooksPropensityBatchTickRoute
  '/api/public/hooks/refresh-recommendations': typeof ApiPublicHooksRefreshRecommendationsRoute
  '/api/public/hooks/sequence-tick': typeof ApiPublicHooksSequenceTickRoute
  '/api/public/hooks/whatsapp-outbox-tick': typeof ApiPublicHooksWhatsappOutboxTickRoute
  '/api/public/hooks/whatsapp-webhook/$channelId': typeof ApiPublicHooksWhatsappWebhookChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activities': typeof AppActivitiesRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/calendar': typeof AppCalendarRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/carteira': typeof AppCarteiraRoute
  '/chat': typeof AppChatRoute
  '/coaching': typeof AppCoachingRoute
  '/command': typeof AppCommandRoute
  '/commissions': typeof AppCommissionsRoute
  '/companies': typeof AppCompaniesRouteWithChildren
  '/contacts': typeof AppContactsRouteWithChildren
  '/customer-360': typeof AppCustomer360Route
  '/dashboard': typeof AppDashboardRoute
  '/dashboard-executivo': typeof AppDashboardExecutivoRoute
  '/forecast': typeof AppForecastRoute
  '/geo': typeof AppGeoRoute
  '/geo-cobertura': typeof AppGeoCoberturaRoute
  '/geo-prospeccao': typeof AppGeoProspeccaoRoute
  '/geo-rota': typeof AppGeoRotaRoute
  '/gestao-visao-global': typeof AppGestaoVisaoGlobalRoute
  '/goals': typeof AppGoalsRoute
  '/influencers': typeof AppInfluencersRoute
  '/integrations': typeof AppIntegrationsRouteWithChildren
  '/inteligencia-comercial': typeof AppInteligenciaComercialRouteWithChildren
  '/lead-forms': typeof AppLeadFormsRoute
  '/leads': typeof AppLeadsRoute
  '/marketing-intel': typeof AppMarketingIntelRoute
  '/meu-dia': typeof AppMeuDiaRoute
  '/multi-empresa': typeof AppMultiEmpresaRouteWithChildren
  '/mytasks': typeof AppMytasksRoute
  '/nba': typeof AppNbaRoute
  '/oportunidades': typeof AppOportunidadesRoute
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/representantes': typeof AppRepresentantesRoute
  '/retention': typeof AppRetentionRoute
  '/sequences': typeof AppSequencesRouteWithChildren
  '/setup-wizard': typeof AppSetupWizardRoute
  '/site-chat': typeof AppSiteChatRoute
  '/welcome': typeof AppWelcomeRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/win-loss': typeof AppWinLossRoute
  '/p/$token': typeof PTokenRoute
  '/campaigns/whatsapp': typeof AppCampaignsWhatsappRoute
  '/companies/$id': typeof AppCompaniesIdRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/integrations/advanced': typeof AppIntegrationsAdvancedRoute
  '/integrations/agent': typeof AppIntegrationsAgentRoute
  '/integrations/apps': typeof AppIntegrationsAppsRoute
  '/integrations/conflicts': typeof AppIntegrationsConflictsRoute
  '/integrations/connect': typeof AppIntegrationsConnectRouteWithChildren
  '/integrations/dashboard': typeof AppIntegrationsDashboardRoute
  '/integrations/diagnostic': typeof AppIntegrationsDiagnosticRoute
  '/integrations/health': typeof AppIntegrationsHealthRoute
  '/integrations/help': typeof AppIntegrationsHelpRoute
  '/integrations/mapping': typeof AppIntegrationsMappingRoute
  '/integrations/outbox': typeof AppIntegrationsOutboxRoute
  '/integrations/smoke-test': typeof AppIntegrationsSmokeTestRoute
  '/integrations/templates': typeof AppIntegrationsTemplatesRoute
  '/inteligencia-comercial/qualidade-ia': typeof AppInteligenciaComercialQualidadeIaRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/multi-empresa/$orgId': typeof AppMultiEmpresaOrgIdRoute
  '/reports/dashboards': typeof AppReportsDashboardsRouteWithChildren
  '/reports/weekly': typeof AppReportsWeeklyRoute
  '/sequences/$id': typeof AppSequencesIdRoute
  '/settings/alerts': typeof AppSettingsAlertsRoute
  '/settings/automations': typeof AppSettingsAutomationsRouteWithChildren
  '/settings/briefing': typeof AppSettingsBriefingRoute
  '/settings/erp-agent': typeof AppSettingsErpAgentRoute
  '/settings/fields': typeof AppSettingsFieldsRoute
  '/settings/import': typeof AppSettingsImportRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/site-chat': typeof AppSettingsSiteChatRoute
  '/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/settings/whatsapp': typeof AppSettingsWhatsappRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/influencer-visit': typeof ApiPublicInfluencerVisitRoute
  '/api/public/lead-form': typeof ApiPublicLeadFormRoute
  '/api/public/site-chat': typeof ApiPublicSiteChatRoute
  '/api/public/site-chat-widget.js': typeof ApiPublicSiteChatWidgetDotjsRoute
  '/i/$org/$slug': typeof IOrgSlugRoute
  '/integrations/connect/wizard': typeof AppIntegrationsConnectWizardRoute
  '/reports/dashboards/$id': typeof AppReportsDashboardsIdRoute
  '/settings/automations/runs': typeof AppSettingsAutomationsRunsRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/initiate': typeof ApiOauthGoogleInitiateRoute
  '/api/public/hooks/activity-reminders': typeof ApiPublicHooksActivityRemindersRoute
  '/api/public/hooks/ai-purge-expired': typeof ApiPublicHooksAiPurgeExpiredRoute
  '/api/public/hooks/campaign-tick': typeof ApiPublicHooksCampaignTickRoute
  '/api/public/hooks/customer-360-refresh': typeof ApiPublicHooksCustomer360RefreshRoute
  '/api/public/hooks/daily-briefing': typeof ApiPublicHooksDailyBriefingRoute
  '/api/public/hooks/erp-agent-push': typeof ApiPublicHooksErpAgentPushRoute
  '/api/public/hooks/erp-inbound': typeof ApiPublicHooksErpInboundRoute
  '/api/public/hooks/erp-local-agent-heartbeat': typeof ApiPublicHooksErpLocalAgentHeartbeatRoute
  '/api/public/hooks/erp-local-agent-pair': typeof ApiPublicHooksErpLocalAgentPairRoute
  '/api/public/hooks/erp-outbox-tick': typeof ApiPublicHooksErpOutboxTickRoute
  '/api/public/hooks/erp-sync-tick': typeof ApiPublicHooksErpSyncTickRoute
  '/api/public/hooks/generate-alerts': typeof ApiPublicHooksGenerateAlertsRoute
  '/api/public/hooks/propensity-batch-tick': typeof ApiPublicHooksPropensityBatchTickRoute
  '/api/public/hooks/refresh-recommendations': typeof ApiPublicHooksRefreshRecommendationsRoute
  '/api/public/hooks/sequence-tick': typeof ApiPublicHooksSequenceTickRoute
  '/api/public/hooks/whatsapp-outbox-tick': typeof ApiPublicHooksWhatsappOutboxTickRoute
  '/api/public/hooks/whatsapp-webhook/$channelId': typeof ApiPublicHooksWhatsappWebhookChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/automacoes': typeof AppAutomacoesRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/campaigns': typeof AppCampaignsRouteWithChildren
  '/_app/carteira': typeof AppCarteiraRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/coaching': typeof AppCoachingRoute
  '/_app/command': typeof AppCommandRoute
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/companies': typeof AppCompaniesRouteWithChildren
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/customer-360': typeof AppCustomer360Route
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dashboard-executivo': typeof AppDashboardExecutivoRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/geo': typeof AppGeoRoute
  '/_app/geo-cobertura': typeof AppGeoCoberturaRoute
  '/_app/geo-prospeccao': typeof AppGeoProspeccaoRoute
  '/_app/geo-rota': typeof AppGeoRotaRoute
  '/_app/gestao-visao-global': typeof AppGestaoVisaoGlobalRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/influencers': typeof AppInfluencersRoute
  '/_app/integrations': typeof AppIntegrationsRouteWithChildren
  '/_app/inteligencia-comercial': typeof AppInteligenciaComercialRouteWithChildren
  '/_app/lead-forms': typeof AppLeadFormsRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/marketing-intel': typeof AppMarketingIntelRoute
  '/_app/meu-dia': typeof AppMeuDiaRoute
  '/_app/multi-empresa': typeof AppMultiEmpresaRouteWithChildren
  '/_app/mytasks': typeof AppMytasksRoute
  '/_app/nba': typeof AppNbaRoute
  '/_app/oportunidades': typeof AppOportunidadesRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/representantes': typeof AppRepresentantesRoute
  '/_app/retention': typeof AppRetentionRoute
  '/_app/sequences': typeof AppSequencesRouteWithChildren
  '/_app/setup-wizard': typeof AppSetupWizardRoute
  '/_app/site-chat': typeof AppSiteChatRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/win-loss': typeof AppWinLossRoute
  '/p/$token': typeof PTokenRoute
  '/_app/campaigns/whatsapp': typeof AppCampaignsWhatsappRoute
  '/_app/companies/$id': typeof AppCompaniesIdRoute
  '/_app/contacts/$id': typeof AppContactsIdRoute
  '/_app/integrations/advanced': typeof AppIntegrationsAdvancedRoute
  '/_app/integrations/agent': typeof AppIntegrationsAgentRoute
  '/_app/integrations/apps': typeof AppIntegrationsAppsRoute
  '/_app/integrations/conflicts': typeof AppIntegrationsConflictsRoute
  '/_app/integrations/connect': typeof AppIntegrationsConnectRouteWithChildren
  '/_app/integrations/dashboard': typeof AppIntegrationsDashboardRoute
  '/_app/integrations/diagnostic': typeof AppIntegrationsDiagnosticRoute
  '/_app/integrations/health': typeof AppIntegrationsHealthRoute
  '/_app/integrations/help': typeof AppIntegrationsHelpRoute
  '/_app/integrations/mapping': typeof AppIntegrationsMappingRoute
  '/_app/integrations/outbox': typeof AppIntegrationsOutboxRoute
  '/_app/integrations/smoke-test': typeof AppIntegrationsSmokeTestRoute
  '/_app/integrations/templates': typeof AppIntegrationsTemplatesRoute
  '/_app/inteligencia-comercial/qualidade-ia': typeof AppInteligenciaComercialQualidadeIaRoute
  '/_app/invite/$token': typeof AppInviteTokenRoute
  '/_app/multi-empresa/$orgId': typeof AppMultiEmpresaOrgIdRoute
  '/_app/reports/dashboards': typeof AppReportsDashboardsRouteWithChildren
  '/_app/reports/weekly': typeof AppReportsWeeklyRoute
  '/_app/sequences/$id': typeof AppSequencesIdRoute
  '/_app/settings/alerts': typeof AppSettingsAlertsRoute
  '/_app/settings/automations': typeof AppSettingsAutomationsRouteWithChildren
  '/_app/settings/briefing': typeof AppSettingsBriefingRoute
  '/_app/settings/erp-agent': typeof AppSettingsErpAgentRoute
  '/_app/settings/fields': typeof AppSettingsFieldsRoute
  '/_app/settings/import': typeof AppSettingsImportRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/organization': typeof AppSettingsOrganizationRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/settings/site-chat': typeof AppSettingsSiteChatRoute
  '/_app/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/_app/settings/whatsapp': typeof AppSettingsWhatsappRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/influencer-visit': typeof ApiPublicInfluencerVisitRoute
  '/api/public/lead-form': typeof ApiPublicLeadFormRoute
  '/api/public/site-chat': typeof ApiPublicSiteChatRoute
  '/api/public/site-chat-widget.js': typeof ApiPublicSiteChatWidgetDotjsRoute
  '/i/$org/$slug': typeof IOrgSlugRoute
  '/_app/integrations/connect/wizard': typeof AppIntegrationsConnectWizardRoute
  '/_app/reports/dashboards/$id': typeof AppReportsDashboardsIdRoute
  '/_app/settings/automations/runs': typeof AppSettingsAutomationsRunsRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/initiate': typeof ApiOauthGoogleInitiateRoute
  '/api/public/hooks/activity-reminders': typeof ApiPublicHooksActivityRemindersRoute
  '/api/public/hooks/ai-purge-expired': typeof ApiPublicHooksAiPurgeExpiredRoute
  '/api/public/hooks/campaign-tick': typeof ApiPublicHooksCampaignTickRoute
  '/api/public/hooks/customer-360-refresh': typeof ApiPublicHooksCustomer360RefreshRoute
  '/api/public/hooks/daily-briefing': typeof ApiPublicHooksDailyBriefingRoute
  '/api/public/hooks/erp-agent-push': typeof ApiPublicHooksErpAgentPushRoute
  '/api/public/hooks/erp-inbound': typeof ApiPublicHooksErpInboundRoute
  '/api/public/hooks/erp-local-agent-heartbeat': typeof ApiPublicHooksErpLocalAgentHeartbeatRoute
  '/api/public/hooks/erp-local-agent-pair': typeof ApiPublicHooksErpLocalAgentPairRoute
  '/api/public/hooks/erp-outbox-tick': typeof ApiPublicHooksErpOutboxTickRoute
  '/api/public/hooks/erp-sync-tick': typeof ApiPublicHooksErpSyncTickRoute
  '/api/public/hooks/generate-alerts': typeof ApiPublicHooksGenerateAlertsRoute
  '/api/public/hooks/propensity-batch-tick': typeof ApiPublicHooksPropensityBatchTickRoute
  '/api/public/hooks/refresh-recommendations': typeof ApiPublicHooksRefreshRecommendationsRoute
  '/api/public/hooks/sequence-tick': typeof ApiPublicHooksSequenceTickRoute
  '/api/public/hooks/whatsapp-outbox-tick': typeof ApiPublicHooksWhatsappOutboxTickRoute
  '/api/public/hooks/whatsapp-webhook/$channelId': typeof ApiPublicHooksWhatsappWebhookChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activities'
    | '/automacoes'
    | '/calendar'
    | '/campaigns'
    | '/carteira'
    | '/chat'
    | '/coaching'
    | '/command'
    | '/commissions'
    | '/companies'
    | '/contacts'
    | '/customer-360'
    | '/dashboard'
    | '/dashboard-executivo'
    | '/forecast'
    | '/geo'
    | '/geo-cobertura'
    | '/geo-prospeccao'
    | '/geo-rota'
    | '/gestao-visao-global'
    | '/goals'
    | '/influencers'
    | '/integrations'
    | '/inteligencia-comercial'
    | '/lead-forms'
    | '/leads'
    | '/marketing-intel'
    | '/meu-dia'
    | '/multi-empresa'
    | '/mytasks'
    | '/nba'
    | '/oportunidades'
    | '/pipeline'
    | '/reports'
    | '/representantes'
    | '/retention'
    | '/sequences'
    | '/setup-wizard'
    | '/site-chat'
    | '/welcome'
    | '/whatsapp'
    | '/win-loss'
    | '/p/$token'
    | '/campaigns/whatsapp'
    | '/companies/$id'
    | '/contacts/$id'
    | '/integrations/advanced'
    | '/integrations/agent'
    | '/integrations/apps'
    | '/integrations/conflicts'
    | '/integrations/connect'
    | '/integrations/dashboard'
    | '/integrations/diagnostic'
    | '/integrations/health'
    | '/integrations/help'
    | '/integrations/mapping'
    | '/integrations/outbox'
    | '/integrations/smoke-test'
    | '/integrations/templates'
    | '/inteligencia-comercial/qualidade-ia'
    | '/invite/$token'
    | '/multi-empresa/$orgId'
    | '/reports/dashboards'
    | '/reports/weekly'
    | '/sequences/$id'
    | '/settings/alerts'
    | '/settings/automations'
    | '/settings/briefing'
    | '/settings/erp-agent'
    | '/settings/fields'
    | '/settings/import'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/security'
    | '/settings/site-chat'
    | '/settings/webhooks'
    | '/settings/whatsapp'
    | '/api/public/inbound-email'
    | '/api/public/influencer-visit'
    | '/api/public/lead-form'
    | '/api/public/site-chat'
    | '/api/public/site-chat-widget.js'
    | '/i/$org/$slug'
    | '/integrations/connect/wizard'
    | '/reports/dashboards/$id'
    | '/settings/automations/runs'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/initiate'
    | '/api/public/hooks/activity-reminders'
    | '/api/public/hooks/ai-purge-expired'
    | '/api/public/hooks/campaign-tick'
    | '/api/public/hooks/customer-360-refresh'
    | '/api/public/hooks/daily-briefing'
    | '/api/public/hooks/erp-agent-push'
    | '/api/public/hooks/erp-inbound'
    | '/api/public/hooks/erp-local-agent-heartbeat'
    | '/api/public/hooks/erp-local-agent-pair'
    | '/api/public/hooks/erp-outbox-tick'
    | '/api/public/hooks/erp-sync-tick'
    | '/api/public/hooks/generate-alerts'
    | '/api/public/hooks/propensity-batch-tick'
    | '/api/public/hooks/refresh-recommendations'
    | '/api/public/hooks/sequence-tick'
    | '/api/public/hooks/whatsapp-outbox-tick'
    | '/api/public/hooks/whatsapp-webhook/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activities'
    | '/automacoes'
    | '/calendar'
    | '/campaigns'
    | '/carteira'
    | '/chat'
    | '/coaching'
    | '/command'
    | '/commissions'
    | '/companies'
    | '/contacts'
    | '/customer-360'
    | '/dashboard'
    | '/dashboard-executivo'
    | '/forecast'
    | '/geo'
    | '/geo-cobertura'
    | '/geo-prospeccao'
    | '/geo-rota'
    | '/gestao-visao-global'
    | '/goals'
    | '/influencers'
    | '/integrations'
    | '/inteligencia-comercial'
    | '/lead-forms'
    | '/leads'
    | '/marketing-intel'
    | '/meu-dia'
    | '/multi-empresa'
    | '/mytasks'
    | '/nba'
    | '/oportunidades'
    | '/pipeline'
    | '/reports'
    | '/representantes'
    | '/retention'
    | '/sequences'
    | '/setup-wizard'
    | '/site-chat'
    | '/welcome'
    | '/whatsapp'
    | '/win-loss'
    | '/p/$token'
    | '/campaigns/whatsapp'
    | '/companies/$id'
    | '/contacts/$id'
    | '/integrations/advanced'
    | '/integrations/agent'
    | '/integrations/apps'
    | '/integrations/conflicts'
    | '/integrations/connect'
    | '/integrations/dashboard'
    | '/integrations/diagnostic'
    | '/integrations/health'
    | '/integrations/help'
    | '/integrations/mapping'
    | '/integrations/outbox'
    | '/integrations/smoke-test'
    | '/integrations/templates'
    | '/inteligencia-comercial/qualidade-ia'
    | '/invite/$token'
    | '/multi-empresa/$orgId'
    | '/reports/dashboards'
    | '/reports/weekly'
    | '/sequences/$id'
    | '/settings/alerts'
    | '/settings/automations'
    | '/settings/briefing'
    | '/settings/erp-agent'
    | '/settings/fields'
    | '/settings/import'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/security'
    | '/settings/site-chat'
    | '/settings/webhooks'
    | '/settings/whatsapp'
    | '/api/public/inbound-email'
    | '/api/public/influencer-visit'
    | '/api/public/lead-form'
    | '/api/public/site-chat'
    | '/api/public/site-chat-widget.js'
    | '/i/$org/$slug'
    | '/integrations/connect/wizard'
    | '/reports/dashboards/$id'
    | '/settings/automations/runs'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/initiate'
    | '/api/public/hooks/activity-reminders'
    | '/api/public/hooks/ai-purge-expired'
    | '/api/public/hooks/campaign-tick'
    | '/api/public/hooks/customer-360-refresh'
    | '/api/public/hooks/daily-briefing'
    | '/api/public/hooks/erp-agent-push'
    | '/api/public/hooks/erp-inbound'
    | '/api/public/hooks/erp-local-agent-heartbeat'
    | '/api/public/hooks/erp-local-agent-pair'
    | '/api/public/hooks/erp-outbox-tick'
    | '/api/public/hooks/erp-sync-tick'
    | '/api/public/hooks/generate-alerts'
    | '/api/public/hooks/propensity-batch-tick'
    | '/api/public/hooks/refresh-recommendations'
    | '/api/public/hooks/sequence-tick'
    | '/api/public/hooks/whatsapp-outbox-tick'
    | '/api/public/hooks/whatsapp-webhook/$channelId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/activities'
    | '/_app/automacoes'
    | '/_app/calendar'
    | '/_app/campaigns'
    | '/_app/carteira'
    | '/_app/chat'
    | '/_app/coaching'
    | '/_app/command'
    | '/_app/commissions'
    | '/_app/companies'
    | '/_app/contacts'
    | '/_app/customer-360'
    | '/_app/dashboard'
    | '/_app/dashboard-executivo'
    | '/_app/forecast'
    | '/_app/geo'
    | '/_app/geo-cobertura'
    | '/_app/geo-prospeccao'
    | '/_app/geo-rota'
    | '/_app/gestao-visao-global'
    | '/_app/goals'
    | '/_app/influencers'
    | '/_app/integrations'
    | '/_app/inteligencia-comercial'
    | '/_app/lead-forms'
    | '/_app/leads'
    | '/_app/marketing-intel'
    | '/_app/meu-dia'
    | '/_app/multi-empresa'
    | '/_app/mytasks'
    | '/_app/nba'
    | '/_app/oportunidades'
    | '/_app/pipeline'
    | '/_app/reports'
    | '/_app/representantes'
    | '/_app/retention'
    | '/_app/sequences'
    | '/_app/setup-wizard'
    | '/_app/site-chat'
    | '/_app/welcome'
    | '/_app/whatsapp'
    | '/_app/win-loss'
    | '/p/$token'
    | '/_app/campaigns/whatsapp'
    | '/_app/companies/$id'
    | '/_app/contacts/$id'
    | '/_app/integrations/advanced'
    | '/_app/integrations/agent'
    | '/_app/integrations/apps'
    | '/_app/integrations/conflicts'
    | '/_app/integrations/connect'
    | '/_app/integrations/dashboard'
    | '/_app/integrations/diagnostic'
    | '/_app/integrations/health'
    | '/_app/integrations/help'
    | '/_app/integrations/mapping'
    | '/_app/integrations/outbox'
    | '/_app/integrations/smoke-test'
    | '/_app/integrations/templates'
    | '/_app/inteligencia-comercial/qualidade-ia'
    | '/_app/invite/$token'
    | '/_app/multi-empresa/$orgId'
    | '/_app/reports/dashboards'
    | '/_app/reports/weekly'
    | '/_app/sequences/$id'
    | '/_app/settings/alerts'
    | '/_app/settings/automations'
    | '/_app/settings/briefing'
    | '/_app/settings/erp-agent'
    | '/_app/settings/fields'
    | '/_app/settings/import'
    | '/_app/settings/notifications'
    | '/_app/settings/organization'
    | '/_app/settings/security'
    | '/_app/settings/site-chat'
    | '/_app/settings/webhooks'
    | '/_app/settings/whatsapp'
    | '/api/public/inbound-email'
    | '/api/public/influencer-visit'
    | '/api/public/lead-form'
    | '/api/public/site-chat'
    | '/api/public/site-chat-widget.js'
    | '/i/$org/$slug'
    | '/_app/integrations/connect/wizard'
    | '/_app/reports/dashboards/$id'
    | '/_app/settings/automations/runs'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/initiate'
    | '/api/public/hooks/activity-reminders'
    | '/api/public/hooks/ai-purge-expired'
    | '/api/public/hooks/campaign-tick'
    | '/api/public/hooks/customer-360-refresh'
    | '/api/public/hooks/daily-briefing'
    | '/api/public/hooks/erp-agent-push'
    | '/api/public/hooks/erp-inbound'
    | '/api/public/hooks/erp-local-agent-heartbeat'
    | '/api/public/hooks/erp-local-agent-pair'
    | '/api/public/hooks/erp-outbox-tick'
    | '/api/public/hooks/erp-sync-tick'
    | '/api/public/hooks/generate-alerts'
    | '/api/public/hooks/propensity-batch-tick'
    | '/api/public/hooks/refresh-recommendations'
    | '/api/public/hooks/sequence-tick'
    | '/api/public/hooks/whatsapp-outbox-tick'
    | '/api/public/hooks/whatsapp-webhook/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PTokenRoute: typeof PTokenRoute
  ApiPublicInboundEmailRoute: typeof ApiPublicInboundEmailRoute
  ApiPublicInfluencerVisitRoute: typeof ApiPublicInfluencerVisitRoute
  ApiPublicLeadFormRoute: typeof ApiPublicLeadFormRoute
  ApiPublicSiteChatRoute: typeof ApiPublicSiteChatRoute
  ApiPublicSiteChatWidgetDotjsRoute: typeof ApiPublicSiteChatWidgetDotjsRoute
  IOrgSlugRoute: typeof IOrgSlugRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
  ApiOauthGoogleInitiateRoute: typeof ApiOauthGoogleInitiateRoute
  ApiPublicHooksActivityRemindersRoute: typeof ApiPublicHooksActivityRemindersRoute
  ApiPublicHooksAiPurgeExpiredRoute: typeof ApiPublicHooksAiPurgeExpiredRoute
  ApiPublicHooksCampaignTickRoute: typeof ApiPublicHooksCampaignTickRoute
  ApiPublicHooksCustomer360RefreshRoute: typeof ApiPublicHooksCustomer360RefreshRoute
  ApiPublicHooksDailyBriefingRoute: typeof ApiPublicHooksDailyBriefingRoute
  ApiPublicHooksErpAgentPushRoute: typeof ApiPublicHooksErpAgentPushRoute
  ApiPublicHooksErpInboundRoute: typeof ApiPublicHooksErpInboundRoute
  ApiPublicHooksErpLocalAgentHeartbeatRoute: typeof ApiPublicHooksErpLocalAgentHeartbeatRoute
  ApiPublicHooksErpLocalAgentPairRoute: typeof ApiPublicHooksErpLocalAgentPairRoute
  ApiPublicHooksErpOutboxTickRoute: typeof ApiPublicHooksErpOutboxTickRoute
  ApiPublicHooksErpSyncTickRoute: typeof ApiPublicHooksErpSyncTickRoute
  ApiPublicHooksGenerateAlertsRoute: typeof ApiPublicHooksGenerateAlertsRoute
  ApiPublicHooksPropensityBatchTickRoute: typeof ApiPublicHooksPropensityBatchTickRoute
  ApiPublicHooksRefreshRecommendationsRoute: typeof ApiPublicHooksRefreshRecommendationsRoute
  ApiPublicHooksSequenceTickRoute: typeof ApiPublicHooksSequenceTickRoute
  ApiPublicHooksWhatsappOutboxTickRoute: typeof ApiPublicHooksWhatsappOutboxTickRoute
  ApiPublicHooksWhatsappWebhookChannelIdRoute: typeof ApiPublicHooksWhatsappWebhookChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/win-loss': {
      id: '/_app/win-loss'
      path: '/win-loss'
      fullPath: '/win-loss'
      preLoaderRoute: typeof AppWinLossRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/site-chat': {
      id: '/_app/site-chat'
      path: '/site-chat'
      fullPath: '/site-chat'
      preLoaderRoute: typeof AppSiteChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup-wizard': {
      id: '/_app/setup-wizard'
      path: '/setup-wizard'
      fullPath: '/setup-wizard'
      preLoaderRoute: typeof AppSetupWizardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sequences': {
      id: '/_app/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof AppSequencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/retention': {
      id: '/_app/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof AppRetentionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/representantes': {
      id: '/_app/representantes'
      path: '/representantes'
      fullPath: '/representantes'
      preLoaderRoute: typeof AppRepresentantesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oportunidades': {
      id: '/_app/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AppOportunidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nba': {
      id: '/_app/nba'
      path: '/nba'
      fullPath: '/nba'
      preLoaderRoute: typeof AppNbaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mytasks': {
      id: '/_app/mytasks'
      path: '/mytasks'
      fullPath: '/mytasks'
      preLoaderRoute: typeof AppMytasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/multi-empresa': {
      id: '/_app/multi-empresa'
      path: '/multi-empresa'
      fullPath: '/multi-empresa'
      preLoaderRoute: typeof AppMultiEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meu-dia': {
      id: '/_app/meu-dia'
      path: '/meu-dia'
      fullPath: '/meu-dia'
      preLoaderRoute: typeof AppMeuDiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing-intel': {
      id: '/_app/marketing-intel'
      path: '/marketing-intel'
      fullPath: '/marketing-intel'
      preLoaderRoute: typeof AppMarketingIntelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lead-forms': {
      id: '/_app/lead-forms'
      path: '/lead-forms'
      fullPath: '/lead-forms'
      preLoaderRoute: typeof AppLeadFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inteligencia-comercial': {
      id: '/_app/inteligencia-comercial'
      path: '/inteligencia-comercial'
      fullPath: '/inteligencia-comercial'
      preLoaderRoute: typeof AppInteligenciaComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/influencers': {
      id: '/_app/influencers'
      path: '/influencers'
      fullPath: '/influencers'
      preLoaderRoute: typeof AppInfluencersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestao-visao-global': {
      id: '/_app/gestao-visao-global'
      path: '/gestao-visao-global'
      fullPath: '/gestao-visao-global'
      preLoaderRoute: typeof AppGestaoVisaoGlobalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/geo-rota': {
      id: '/_app/geo-rota'
      path: '/geo-rota'
      fullPath: '/geo-rota'
      preLoaderRoute: typeof AppGeoRotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/geo-prospeccao': {
      id: '/_app/geo-prospeccao'
      path: '/geo-prospeccao'
      fullPath: '/geo-prospeccao'
      preLoaderRoute: typeof AppGeoProspeccaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/geo-cobertura': {
      id: '/_app/geo-cobertura'
      path: '/geo-cobertura'
      fullPath: '/geo-cobertura'
      preLoaderRoute: typeof AppGeoCoberturaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/geo': {
      id: '/_app/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof AppGeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard-executivo': {
      id: '/_app/dashboard-executivo'
      path: '/dashboard-executivo'
      fullPath: '/dashboard-executivo'
      preLoaderRoute: typeof AppDashboardExecutivoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customer-360': {
      id: '/_app/customer-360'
      path: '/customer-360'
      fullPath: '/customer-360'
      preLoaderRoute: typeof AppCustomer360RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/command': {
      id: '/_app/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AppCommandRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coaching': {
      id: '/_app/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof AppCoachingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carteira': {
      id: '/_app/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AppCarteiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automacoes': {
      id: '/_app/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/i/$org/$slug': {
      id: '/i/$org/$slug'
      path: '/i/$org/$slug'
      fullPath: '/i/$org/$slug'
      preLoaderRoute: typeof IOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-chat-widget.js': {
      id: '/api/public/site-chat-widget.js'
      path: '/api/public/site-chat-widget.js'
      fullPath: '/api/public/site-chat-widget.js'
      preLoaderRoute: typeof ApiPublicSiteChatWidgetDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-chat': {
      id: '/api/public/site-chat'
      path: '/api/public/site-chat'
      fullPath: '/api/public/site-chat'
      preLoaderRoute: typeof ApiPublicSiteChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-form': {
      id: '/api/public/lead-form'
      path: '/api/public/lead-form'
      fullPath: '/api/public/lead-form'
      preLoaderRoute: typeof ApiPublicLeadFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/influencer-visit': {
      id: '/api/public/influencer-visit'
      path: '/api/public/influencer-visit'
      fullPath: '/api/public/influencer-visit'
      preLoaderRoute: typeof ApiPublicInfluencerVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound-email': {
      id: '/api/public/inbound-email'
      path: '/api/public/inbound-email'
      fullPath: '/api/public/inbound-email'
      preLoaderRoute: typeof ApiPublicInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/whatsapp': {
      id: '/_app/settings/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof AppSettingsWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/webhooks': {
      id: '/_app/settings/webhooks'
      path: '/settings/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AppSettingsWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/site-chat': {
      id: '/_app/settings/site-chat'
      path: '/settings/site-chat'
      fullPath: '/settings/site-chat'
      preLoaderRoute: typeof AppSettingsSiteChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/import': {
      id: '/_app/settings/import'
      path: '/settings/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof AppSettingsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/fields': {
      id: '/_app/settings/fields'
      path: '/settings/fields'
      fullPath: '/settings/fields'
      preLoaderRoute: typeof AppSettingsFieldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/erp-agent': {
      id: '/_app/settings/erp-agent'
      path: '/settings/erp-agent'
      fullPath: '/settings/erp-agent'
      preLoaderRoute: typeof AppSettingsErpAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/briefing': {
      id: '/_app/settings/briefing'
      path: '/settings/briefing'
      fullPath: '/settings/briefing'
      preLoaderRoute: typeof AppSettingsBriefingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/automations': {
      id: '/_app/settings/automations'
      path: '/settings/automations'
      fullPath: '/settings/automations'
      preLoaderRoute: typeof AppSettingsAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/alerts': {
      id: '/_app/settings/alerts'
      path: '/settings/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof AppSettingsAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sequences/$id': {
      id: '/_app/sequences/$id'
      path: '/$id'
      fullPath: '/sequences/$id'
      preLoaderRoute: typeof AppSequencesIdRouteImport
      parentRoute: typeof AppSequencesRoute
    }
    '/_app/reports/weekly': {
      id: '/_app/reports/weekly'
      path: '/weekly'
      fullPath: '/reports/weekly'
      preLoaderRoute: typeof AppReportsWeeklyRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/dashboards': {
      id: '/_app/reports/dashboards'
      path: '/dashboards'
      fullPath: '/reports/dashboards'
      preLoaderRoute: typeof AppReportsDashboardsRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/multi-empresa/$orgId': {
      id: '/_app/multi-empresa/$orgId'
      path: '/$orgId'
      fullPath: '/multi-empresa/$orgId'
      preLoaderRoute: typeof AppMultiEmpresaOrgIdRouteImport
      parentRoute: typeof AppMultiEmpresaRoute
    }
    '/_app/invite/$token': {
      id: '/_app/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AppInviteTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inteligencia-comercial/qualidade-ia': {
      id: '/_app/inteligencia-comercial/qualidade-ia'
      path: '/qualidade-ia'
      fullPath: '/inteligencia-comercial/qualidade-ia'
      preLoaderRoute: typeof AppInteligenciaComercialQualidadeIaRouteImport
      parentRoute: typeof AppInteligenciaComercialRoute
    }
    '/_app/integrations/templates': {
      id: '/_app/integrations/templates'
      path: '/templates'
      fullPath: '/integrations/templates'
      preLoaderRoute: typeof AppIntegrationsTemplatesRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/smoke-test': {
      id: '/_app/integrations/smoke-test'
      path: '/smoke-test'
      fullPath: '/integrations/smoke-test'
      preLoaderRoute: typeof AppIntegrationsSmokeTestRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/outbox': {
      id: '/_app/integrations/outbox'
      path: '/outbox'
      fullPath: '/integrations/outbox'
      preLoaderRoute: typeof AppIntegrationsOutboxRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/mapping': {
      id: '/_app/integrations/mapping'
      path: '/mapping'
      fullPath: '/integrations/mapping'
      preLoaderRoute: typeof AppIntegrationsMappingRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/help': {
      id: '/_app/integrations/help'
      path: '/help'
      fullPath: '/integrations/help'
      preLoaderRoute: typeof AppIntegrationsHelpRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/health': {
      id: '/_app/integrations/health'
      path: '/health'
      fullPath: '/integrations/health'
      preLoaderRoute: typeof AppIntegrationsHealthRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/diagnostic': {
      id: '/_app/integrations/diagnostic'
      path: '/diagnostic'
      fullPath: '/integrations/diagnostic'
      preLoaderRoute: typeof AppIntegrationsDiagnosticRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/dashboard': {
      id: '/_app/integrations/dashboard'
      path: '/dashboard'
      fullPath: '/integrations/dashboard'
      preLoaderRoute: typeof AppIntegrationsDashboardRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/connect': {
      id: '/_app/integrations/connect'
      path: '/connect'
      fullPath: '/integrations/connect'
      preLoaderRoute: typeof AppIntegrationsConnectRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/conflicts': {
      id: '/_app/integrations/conflicts'
      path: '/conflicts'
      fullPath: '/integrations/conflicts'
      preLoaderRoute: typeof AppIntegrationsConflictsRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/apps': {
      id: '/_app/integrations/apps'
      path: '/apps'
      fullPath: '/integrations/apps'
      preLoaderRoute: typeof AppIntegrationsAppsRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/agent': {
      id: '/_app/integrations/agent'
      path: '/agent'
      fullPath: '/integrations/agent'
      preLoaderRoute: typeof AppIntegrationsAgentRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/integrations/advanced': {
      id: '/_app/integrations/advanced'
      path: '/advanced'
      fullPath: '/integrations/advanced'
      preLoaderRoute: typeof AppIntegrationsAdvancedRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/_app/contacts/$id': {
      id: '/_app/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/companies/$id': {
      id: '/_app/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AppCompaniesIdRouteImport
      parentRoute: typeof AppCompaniesRoute
    }
    '/_app/campaigns/whatsapp': {
      id: '/_app/campaigns/whatsapp'
      path: '/whatsapp'
      fullPath: '/campaigns/whatsapp'
      preLoaderRoute: typeof AppCampaignsWhatsappRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/api/public/hooks/whatsapp-outbox-tick': {
      id: '/api/public/hooks/whatsapp-outbox-tick'
      path: '/api/public/hooks/whatsapp-outbox-tick'
      fullPath: '/api/public/hooks/whatsapp-outbox-tick'
      preLoaderRoute: typeof ApiPublicHooksWhatsappOutboxTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sequence-tick': {
      id: '/api/public/hooks/sequence-tick'
      path: '/api/public/hooks/sequence-tick'
      fullPath: '/api/public/hooks/sequence-tick'
      preLoaderRoute: typeof ApiPublicHooksSequenceTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-recommendations': {
      id: '/api/public/hooks/refresh-recommendations'
      path: '/api/public/hooks/refresh-recommendations'
      fullPath: '/api/public/hooks/refresh-recommendations'
      preLoaderRoute: typeof ApiPublicHooksRefreshRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/propensity-batch-tick': {
      id: '/api/public/hooks/propensity-batch-tick'
      path: '/api/public/hooks/propensity-batch-tick'
      fullPath: '/api/public/hooks/propensity-batch-tick'
      preLoaderRoute: typeof ApiPublicHooksPropensityBatchTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-alerts': {
      id: '/api/public/hooks/generate-alerts'
      path: '/api/public/hooks/generate-alerts'
      fullPath: '/api/public/hooks/generate-alerts'
      preLoaderRoute: typeof ApiPublicHooksGenerateAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/erp-sync-tick': {
      id: '/api/public/hooks/erp-sync-tick'
      path: '/api/public/hooks/erp-sync-tick'
      fullPath: '/api/public/hooks/erp-sync-tick'
      preLoaderRoute: typeof ApiPublicHooksErpSyncTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/erp-outbox-tick': {
      id: '/api/public/hooks/erp-outbox-tick'
      path: '/api/public/hooks/erp-outbox-tick'
      fullPath: '/api/public/hooks/erp-outbox-tick'
      preLoaderRoute: typeof ApiPublicHooksErpOutboxTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/erp-local-agent-pair': {
      id: '/api/public/hooks/erp-local-agent-pair'
      path: '/api/public/hooks/erp-local-agent-pair'
      fullPath: '/api/public/hooks/erp-local-agent-pair'
      preLoaderRoute: typeof ApiPublicHooksErpLocalAgentPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/erp-local-agent-heartbeat': {
      id: '/api/public/hooks/erp-local-agent-heartbeat'
      path: '/api/public/hooks/erp-local-agent-heartbeat'
      fullPath: '/api/public/hooks/erp-local-agent-heartbeat'
      preLoaderRoute: typeof ApiPublicHooksErpLocalAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/erp-inbound': {
      id: '/api/public/hooks/erp-inbound'
      path: '/api/public/hooks/erp-inbound'
      fullPath: '/api/public/hooks/erp-inbound'
      preLoaderRoute: typeof ApiPublicHooksErpInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/erp-agent-push': {
      id: '/api/public/hooks/erp-agent-push'
      path: '/api/public/hooks/erp-agent-push'
      fullPath: '/api/public/hooks/erp-agent-push'
      preLoaderRoute: typeof ApiPublicHooksErpAgentPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-briefing': {
      id: '/api/public/hooks/daily-briefing'
      path: '/api/public/hooks/daily-briefing'
      fullPath: '/api/public/hooks/daily-briefing'
      preLoaderRoute: typeof ApiPublicHooksDailyBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/customer-360-refresh': {
      id: '/api/public/hooks/customer-360-refresh'
      path: '/api/public/hooks/customer-360-refresh'
      fullPath: '/api/public/hooks/customer-360-refresh'
      preLoaderRoute: typeof ApiPublicHooksCustomer360RefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/campaign-tick': {
      id: '/api/public/hooks/campaign-tick'
      path: '/api/public/hooks/campaign-tick'
      fullPath: '/api/public/hooks/campaign-tick'
      preLoaderRoute: typeof ApiPublicHooksCampaignTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ai-purge-expired': {
      id: '/api/public/hooks/ai-purge-expired'
      path: '/api/public/hooks/ai-purge-expired'
      fullPath: '/api/public/hooks/ai-purge-expired'
      preLoaderRoute: typeof ApiPublicHooksAiPurgeExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/activity-reminders': {
      id: '/api/public/hooks/activity-reminders'
      path: '/api/public/hooks/activity-reminders'
      fullPath: '/api/public/hooks/activity-reminders'
      preLoaderRoute: typeof ApiPublicHooksActivityRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/initiate': {
      id: '/api/oauth/google/initiate'
      path: '/api/oauth/google/initiate'
      fullPath: '/api/oauth/google/initiate'
      preLoaderRoute: typeof ApiOauthGoogleInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/automations/runs': {
      id: '/_app/settings/automations/runs'
      path: '/runs'
      fullPath: '/settings/automations/runs'
      preLoaderRoute: typeof AppSettingsAutomationsRunsRouteImport
      parentRoute: typeof AppSettingsAutomationsRoute
    }
    '/_app/reports/dashboards/$id': {
      id: '/_app/reports/dashboards/$id'
      path: '/$id'
      fullPath: '/reports/dashboards/$id'
      preLoaderRoute: typeof AppReportsDashboardsIdRouteImport
      parentRoute: typeof AppReportsDashboardsRoute
    }
    '/_app/integrations/connect/wizard': {
      id: '/_app/integrations/connect/wizard'
      path: '/wizard'
      fullPath: '/integrations/connect/wizard'
      preLoaderRoute: typeof AppIntegrationsConnectWizardRouteImport
      parentRoute: typeof AppIntegrationsConnectRoute
    }
    '/api/public/hooks/whatsapp-webhook/$channelId': {
      id: '/api/public/hooks/whatsapp-webhook/$channelId'
      path: '/api/public/hooks/whatsapp-webhook/$channelId'
      fullPath: '/api/public/hooks/whatsapp-webhook/$channelId'
      preLoaderRoute: typeof ApiPublicHooksWhatsappWebhookChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsWhatsappRoute: typeof AppCampaignsWhatsappRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsWhatsappRoute: AppCampaignsWhatsappRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppCompaniesRouteChildren {
  AppCompaniesIdRoute: typeof AppCompaniesIdRoute
}

const AppCompaniesRouteChildren: AppCompaniesRouteChildren = {
  AppCompaniesIdRoute: AppCompaniesIdRoute,
}

const AppCompaniesRouteWithChildren = AppCompaniesRoute._addFileChildren(
  AppCompaniesRouteChildren,
)

interface AppContactsRouteChildren {
  AppContactsIdRoute: typeof AppContactsIdRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsIdRoute: AppContactsIdRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppIntegrationsConnectRouteChildren {
  AppIntegrationsConnectWizardRoute: typeof AppIntegrationsConnectWizardRoute
}

const AppIntegrationsConnectRouteChildren: AppIntegrationsConnectRouteChildren =
  {
    AppIntegrationsConnectWizardRoute: AppIntegrationsConnectWizardRoute,
  }

const AppIntegrationsConnectRouteWithChildren =
  AppIntegrationsConnectRoute._addFileChildren(
    AppIntegrationsConnectRouteChildren,
  )

interface AppIntegrationsRouteChildren {
  AppIntegrationsAdvancedRoute: typeof AppIntegrationsAdvancedRoute
  AppIntegrationsAgentRoute: typeof AppIntegrationsAgentRoute
  AppIntegrationsAppsRoute: typeof AppIntegrationsAppsRoute
  AppIntegrationsConflictsRoute: typeof AppIntegrationsConflictsRoute
  AppIntegrationsConnectRoute: typeof AppIntegrationsConnectRouteWithChildren
  AppIntegrationsDashboardRoute: typeof AppIntegrationsDashboardRoute
  AppIntegrationsDiagnosticRoute: typeof AppIntegrationsDiagnosticRoute
  AppIntegrationsHealthRoute: typeof AppIntegrationsHealthRoute
  AppIntegrationsHelpRoute: typeof AppIntegrationsHelpRoute
  AppIntegrationsMappingRoute: typeof AppIntegrationsMappingRoute
  AppIntegrationsOutboxRoute: typeof AppIntegrationsOutboxRoute
  AppIntegrationsSmokeTestRoute: typeof AppIntegrationsSmokeTestRoute
  AppIntegrationsTemplatesRoute: typeof AppIntegrationsTemplatesRoute
}

const AppIntegrationsRouteChildren: AppIntegrationsRouteChildren = {
  AppIntegrationsAdvancedRoute: AppIntegrationsAdvancedRoute,
  AppIntegrationsAgentRoute: AppIntegrationsAgentRoute,
  AppIntegrationsAppsRoute: AppIntegrationsAppsRoute,
  AppIntegrationsConflictsRoute: AppIntegrationsConflictsRoute,
  AppIntegrationsConnectRoute: AppIntegrationsConnectRouteWithChildren,
  AppIntegrationsDashboardRoute: AppIntegrationsDashboardRoute,
  AppIntegrationsDiagnosticRoute: AppIntegrationsDiagnosticRoute,
  AppIntegrationsHealthRoute: AppIntegrationsHealthRoute,
  AppIntegrationsHelpRoute: AppIntegrationsHelpRoute,
  AppIntegrationsMappingRoute: AppIntegrationsMappingRoute,
  AppIntegrationsOutboxRoute: AppIntegrationsOutboxRoute,
  AppIntegrationsSmokeTestRoute: AppIntegrationsSmokeTestRoute,
  AppIntegrationsTemplatesRoute: AppIntegrationsTemplatesRoute,
}

const AppIntegrationsRouteWithChildren = AppIntegrationsRoute._addFileChildren(
  AppIntegrationsRouteChildren,
)

interface AppInteligenciaComercialRouteChildren {
  AppInteligenciaComercialQualidadeIaRoute: typeof AppInteligenciaComercialQualidadeIaRoute
}

const AppInteligenciaComercialRouteChildren: AppInteligenciaComercialRouteChildren =
  {
    AppInteligenciaComercialQualidadeIaRoute:
      AppInteligenciaComercialQualidadeIaRoute,
  }

const AppInteligenciaComercialRouteWithChildren =
  AppInteligenciaComercialRoute._addFileChildren(
    AppInteligenciaComercialRouteChildren,
  )

interface AppMultiEmpresaRouteChildren {
  AppMultiEmpresaOrgIdRoute: typeof AppMultiEmpresaOrgIdRoute
}

const AppMultiEmpresaRouteChildren: AppMultiEmpresaRouteChildren = {
  AppMultiEmpresaOrgIdRoute: AppMultiEmpresaOrgIdRoute,
}

const AppMultiEmpresaRouteWithChildren = AppMultiEmpresaRoute._addFileChildren(
  AppMultiEmpresaRouteChildren,
)

interface AppReportsDashboardsRouteChildren {
  AppReportsDashboardsIdRoute: typeof AppReportsDashboardsIdRoute
}

const AppReportsDashboardsRouteChildren: AppReportsDashboardsRouteChildren = {
  AppReportsDashboardsIdRoute: AppReportsDashboardsIdRoute,
}

const AppReportsDashboardsRouteWithChildren =
  AppReportsDashboardsRoute._addFileChildren(AppReportsDashboardsRouteChildren)

interface AppReportsRouteChildren {
  AppReportsDashboardsRoute: typeof AppReportsDashboardsRouteWithChildren
  AppReportsWeeklyRoute: typeof AppReportsWeeklyRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsDashboardsRoute: AppReportsDashboardsRouteWithChildren,
  AppReportsWeeklyRoute: AppReportsWeeklyRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppSequencesRouteChildren {
  AppSequencesIdRoute: typeof AppSequencesIdRoute
}

const AppSequencesRouteChildren: AppSequencesRouteChildren = {
  AppSequencesIdRoute: AppSequencesIdRoute,
}

const AppSequencesRouteWithChildren = AppSequencesRoute._addFileChildren(
  AppSequencesRouteChildren,
)

interface AppSettingsAutomationsRouteChildren {
  AppSettingsAutomationsRunsRoute: typeof AppSettingsAutomationsRunsRoute
}

const AppSettingsAutomationsRouteChildren: AppSettingsAutomationsRouteChildren =
  {
    AppSettingsAutomationsRunsRoute: AppSettingsAutomationsRunsRoute,
  }

const AppSettingsAutomationsRouteWithChildren =
  AppSettingsAutomationsRoute._addFileChildren(
    AppSettingsAutomationsRouteChildren,
  )

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppCarteiraRoute: typeof AppCarteiraRoute
  AppChatRoute: typeof AppChatRoute
  AppCoachingRoute: typeof AppCoachingRoute
  AppCommandRoute: typeof AppCommandRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppCompaniesRoute: typeof AppCompaniesRouteWithChildren
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppCustomer360Route: typeof AppCustomer360Route
  AppDashboardRoute: typeof AppDashboardRoute
  AppDashboardExecutivoRoute: typeof AppDashboardExecutivoRoute
  AppForecastRoute: typeof AppForecastRoute
  AppGeoRoute: typeof AppGeoRoute
  AppGeoCoberturaRoute: typeof AppGeoCoberturaRoute
  AppGeoProspeccaoRoute: typeof AppGeoProspeccaoRoute
  AppGeoRotaRoute: typeof AppGeoRotaRoute
  AppGestaoVisaoGlobalRoute: typeof AppGestaoVisaoGlobalRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppInfluencersRoute: typeof AppInfluencersRoute
  AppIntegrationsRoute: typeof AppIntegrationsRouteWithChildren
  AppInteligenciaComercialRoute: typeof AppInteligenciaComercialRouteWithChildren
  AppLeadFormsRoute: typeof AppLeadFormsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMarketingIntelRoute: typeof AppMarketingIntelRoute
  AppMeuDiaRoute: typeof AppMeuDiaRoute
  AppMultiEmpresaRoute: typeof AppMultiEmpresaRouteWithChildren
  AppMytasksRoute: typeof AppMytasksRoute
  AppNbaRoute: typeof AppNbaRoute
  AppOportunidadesRoute: typeof AppOportunidadesRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppRepresentantesRoute: typeof AppRepresentantesRoute
  AppRetentionRoute: typeof AppRetentionRoute
  AppSequencesRoute: typeof AppSequencesRouteWithChildren
  AppSetupWizardRoute: typeof AppSetupWizardRoute
  AppSiteChatRoute: typeof AppSiteChatRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppWinLossRoute: typeof AppWinLossRoute
  AppInviteTokenRoute: typeof AppInviteTokenRoute
  AppSettingsAlertsRoute: typeof AppSettingsAlertsRoute
  AppSettingsAutomationsRoute: typeof AppSettingsAutomationsRouteWithChildren
  AppSettingsBriefingRoute: typeof AppSettingsBriefingRoute
  AppSettingsErpAgentRoute: typeof AppSettingsErpAgentRoute
  AppSettingsFieldsRoute: typeof AppSettingsFieldsRoute
  AppSettingsImportRoute: typeof AppSettingsImportRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsSiteChatRoute: typeof AppSettingsSiteChatRoute
  AppSettingsWebhooksRoute: typeof AppSettingsWebhooksRoute
  AppSettingsWhatsappRoute: typeof AppSettingsWhatsappRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppCarteiraRoute: AppCarteiraRoute,
  AppChatRoute: AppChatRoute,
  AppCoachingRoute: AppCoachingRoute,
  AppCommandRoute: AppCommandRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppCompaniesRoute: AppCompaniesRouteWithChildren,
  AppContactsRoute: AppContactsRouteWithChildren,
  AppCustomer360Route: AppCustomer360Route,
  AppDashboardRoute: AppDashboardRoute,
  AppDashboardExecutivoRoute: AppDashboardExecutivoRoute,
  AppForecastRoute: AppForecastRoute,
  AppGeoRoute: AppGeoRoute,
  AppGeoCoberturaRoute: AppGeoCoberturaRoute,
  AppGeoProspeccaoRoute: AppGeoProspeccaoRoute,
  AppGeoRotaRoute: AppGeoRotaRoute,
  AppGestaoVisaoGlobalRoute: AppGestaoVisaoGlobalRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppInfluencersRoute: AppInfluencersRoute,
  AppIntegrationsRoute: AppIntegrationsRouteWithChildren,
  AppInteligenciaComercialRoute: AppInteligenciaComercialRouteWithChildren,
  AppLeadFormsRoute: AppLeadFormsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMarketingIntelRoute: AppMarketingIntelRoute,
  AppMeuDiaRoute: AppMeuDiaRoute,
  AppMultiEmpresaRoute: AppMultiEmpresaRouteWithChildren,
  AppMytasksRoute: AppMytasksRoute,
  AppNbaRoute: AppNbaRoute,
  AppOportunidadesRoute: AppOportunidadesRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppRepresentantesRoute: AppRepresentantesRoute,
  AppRetentionRoute: AppRetentionRoute,
  AppSequencesRoute: AppSequencesRouteWithChildren,
  AppSetupWizardRoute: AppSetupWizardRoute,
  AppSiteChatRoute: AppSiteChatRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppWinLossRoute: AppWinLossRoute,
  AppInviteTokenRoute: AppInviteTokenRoute,
  AppSettingsAlertsRoute: AppSettingsAlertsRoute,
  AppSettingsAutomationsRoute: AppSettingsAutomationsRouteWithChildren,
  AppSettingsBriefingRoute: AppSettingsBriefingRoute,
  AppSettingsErpAgentRoute: AppSettingsErpAgentRoute,
  AppSettingsFieldsRoute: AppSettingsFieldsRoute,
  AppSettingsImportRoute: AppSettingsImportRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsSiteChatRoute: AppSettingsSiteChatRoute,
  AppSettingsWebhooksRoute: AppSettingsWebhooksRoute,
  AppSettingsWhatsappRoute: AppSettingsWhatsappRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PTokenRoute: PTokenRoute,
  ApiPublicInboundEmailRoute: ApiPublicInboundEmailRoute,
  ApiPublicInfluencerVisitRoute: ApiPublicInfluencerVisitRoute,
  ApiPublicLeadFormRoute: ApiPublicLeadFormRoute,
  ApiPublicSiteChatRoute: ApiPublicSiteChatRoute,
  ApiPublicSiteChatWidgetDotjsRoute: ApiPublicSiteChatWidgetDotjsRoute,
  IOrgSlugRoute: IOrgSlugRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
  ApiOauthGoogleInitiateRoute: ApiOauthGoogleInitiateRoute,
  ApiPublicHooksActivityRemindersRoute: ApiPublicHooksActivityRemindersRoute,
  ApiPublicHooksAiPurgeExpiredRoute: ApiPublicHooksAiPurgeExpiredRoute,
  ApiPublicHooksCampaignTickRoute: ApiPublicHooksCampaignTickRoute,
  ApiPublicHooksCustomer360RefreshRoute: ApiPublicHooksCustomer360RefreshRoute,
  ApiPublicHooksDailyBriefingRoute: ApiPublicHooksDailyBriefingRoute,
  ApiPublicHooksErpAgentPushRoute: ApiPublicHooksErpAgentPushRoute,
  ApiPublicHooksErpInboundRoute: ApiPublicHooksErpInboundRoute,
  ApiPublicHooksErpLocalAgentHeartbeatRoute:
    ApiPublicHooksErpLocalAgentHeartbeatRoute,
  ApiPublicHooksErpLocalAgentPairRoute: ApiPublicHooksErpLocalAgentPairRoute,
  ApiPublicHooksErpOutboxTickRoute: ApiPublicHooksErpOutboxTickRoute,
  ApiPublicHooksErpSyncTickRoute: ApiPublicHooksErpSyncTickRoute,
  ApiPublicHooksGenerateAlertsRoute: ApiPublicHooksGenerateAlertsRoute,
  ApiPublicHooksPropensityBatchTickRoute:
    ApiPublicHooksPropensityBatchTickRoute,
  ApiPublicHooksRefreshRecommendationsRoute:
    ApiPublicHooksRefreshRecommendationsRoute,
  ApiPublicHooksSequenceTickRoute: ApiPublicHooksSequenceTickRoute,
  ApiPublicHooksWhatsappOutboxTickRoute: ApiPublicHooksWhatsappOutboxTickRoute,
  ApiPublicHooksWhatsappWebhookChannelIdRoute:
    ApiPublicHooksWhatsappWebhookChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
